/* Generated by tools/mkicons.py. Do not edit. */
#include "Multiverse.r"

resource 'ICN#' (128) {
    {
        $"00000000 0003C000"
        $"0003C000 01FFFF80"
        $"0103C080 0103C080"
        $"01000080 01000080"
        $"7FFC3FFE 40042002"
        $"5FF42FFA 5014280A"
        $"5014280A 55542BEA"
        $"5014280A 5014280A"
        $"5FF42FFA 40042002"
        $"40042002 41E420F2"
        $"40042002 40042002"
        $"7FFC3FFE 3FF81FFC"
        $"3FF81FFC 00000000"
        $"00000000 00000100"
        $"000000C0 07FFFFE0"
        $"000000C0 00000100",
        $"00000000 0003C000"
        $"0003C000 01FFFF80"
        $"0103C080 0103C080"
        $"01000080 01000080"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 7FFC3FFE"
        $"7FFC3FFE 3FF81FFC"
        $"3FF81FFC 00000000"
        $"00000000 00000100"
        $"000000C0 07FFFFE0"
        $"000000C0 00000100"
    }
};

resource 'ics#' (128) {
    {
        $"0180 0FF0 1188 1008"
        $"FE7F FE7F C67B C663"
        $"BE7D 8A4D 8241 7E7E"
        $"7C3E 0000 1FF8 0008",
        $"0180 0FF0 1188 1008"
        $"FE7F FE7F FE7F FE7F"
        $"FE7F FE7F FE7F 7E7E"
        $"7C3E 0000 1FF8 0008"
    }
};

resource 'FREF' (128) { 'APPL', 0, "" };

resource 'BNDL' (128) {
    'LFts', 0,
    {
        'ICN#', { 0, 128 },
        'FREF', { 0, 128 }
    }
};

/* Memory: replaces Retro68's default of 1 MB. */
resource 'SIZE' (-1) {
    reserved, ignoreSuspendResumeEvents, reserved, cannotBackground,
    needsActivateOnFGSwitch, backgroundAndForeground, dontGetFrontClicks,
    ignoreChildDiedEvents, is32BitCompatible, notHighLevelEventAware,
    onlyLocalHLEvents, notStationeryAware, dontUseTextEditServices,
    reserved, reserved, reserved,
    384 * 1024, /* preferred */
    256 * 1024  /* minimum */
};

/* The signature (owner) resource. */
data 'LFts' (0, "Owner resource") { $"06" $"4C4654657374" };
