/* Generated by tools/mkicons.py. Do not edit. */
#include "Multiverse.r"

resource 'ICN#' (128) {
    {
        $"00000000 00000000"
        $"0007E000 00081000"
        $"00100800 00181800"
        $"3F1FF800 40955800"
        $"805AA800 C0D55800"
        $"BF5AA8FC 80555902"
        $"805AAA01 80555B03"
        $"FFDAAAFD D5555A01"
        $"AADAAA01 D5555A01"
        $"AADAAA01 D5555A01"
        $"AADAAA01 D5555BFF"
        $"AADAAAAB D5555B55"
        $"AADAAAAB D5555B55"
        $"BFDFEAFF D5DD5B57"
        $"AADAAAAB 40881102"
        $"3F07E0FC 00000000",
        $"00000000 00000000"
        $"0007E000 000FF000"
        $"001FF800 001FF800"
        $"3F1FF800 7F9FF800"
        $"FFDFF800 FFDFF800"
        $"FFDFF8FC FFDFF9FE"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF FFDFFBFF"
        $"FFDFFBFF 7F8FF1FE"
        $"3F07E0FC 00000000"
    }
};

resource 'ics#' (128) {
    {
        $"0000 03C0 0420 77E0"
        $"8FE0 FFEE 8FF1 FFFF"
        $"FFF1 FFF1 FFFF FFFF"
        $"FFFF FFFF 8A51 718E",
        $"0000 03C0 07E0 77E0"
        $"FFE0 FFEE FFFF FFFF"
        $"FFFF FFFF FFFF FFFF"
        $"FFFF FFFF FBDF 718E"
    }
};

resource 'FREF' (128) { 'APPL', 0, "" };

resource 'BNDL' (128) {
    'LFtk', 0,
    {
        'ICN#', { 0, 128 },
        'FREF', { 0, 128 }
    }
};

/* Memory: replaces Retro68's default of 1 MB. */
resource 'SIZE' (-1) {
    reserved, ignoreSuspendResumeEvents, reserved, cannotBackground,
    needsActivateOnFGSwitch, backgroundAndForeground, dontGetFrontClicks,
    ignoreChildDiedEvents, is32BitCompatible, notHighLevelEventAware,
    onlyLocalHLEvents, notStationeryAware, dontUseTextEditServices,
    reserved, reserved, reserved,
    384 * 1024, /* preferred */
    256 * 1024  /* minimum */
};

/* The signature (owner) resource. */
data 'LFtk' (0, "Owner resource") { $"05" $"54616E6B73" };
