/* Generated by tools/mkicons.py. Do not edit. */
#include "Multiverse.r"

resource 'ICN#' (128) {
    {
        $"00200400 00100800"
        $"00081000 00042000"
        $"00024000 1FFFFFF8"
        $"60000006 40000002"
        $"9FFFFFF9 9FFFFFF9"
        $"9FFEAAB9 9FFFFFF9"
        $"98000019 98888899"
        $"98000019 9FFFFFF9"
        $"9FFFFFF9 980007D9"
        $"9FFFFFF9 98000059"
        $"9FFFFFF9 9FFFFFF9"
        $"9AA0AA09 9D60D609"
        $"9FFFFFF9 9FFFFFF9"
        $"40000002 60000006"
        $"1FFFFFF8 03C003C0"
        $"03C003C0 00000000",
        $"00200400 00100800"
        $"00081000 00042000"
        $"00024000 1FFFFFF8"
        $"7FFFFFFE 7FFFFFFE"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"FFFFFFFF FFFFFFFF"
        $"7FFFFFFE 7FFFFFFE"
        $"1FFFFFF8 03C003C0"
        $"03C003C0 00000000"
    }
};

resource 'ics#' (128) {
    {
        $"0420 0240 3FFC 8001"
        $"FFFF FFFF E007 FFFF"
        $"FFFF FFFF FFFF FCF3"
        $"FFFF 8001 3FFC 1818",
        $"0420 0240 3FFC 8001"
        $"FFFF FFFF FFFF FFFF"
        $"FFFF FFFF FFFF FFFF"
        $"FFFF 8001 3FFC 1818"
    }
};

resource 'FREF' (128) { 'APPL', 0, "" };

resource 'BNDL' (128) {
    'LFtt', 0,
    {
        'ICN#', { 0, 128 },
        'FREF', { 0, 128 }
    }
};

/* Memory: replaces Retro68's default of 1 MB. */
resource 'SIZE' (-1) {
    reserved, ignoreSuspendResumeEvents, reserved, cannotBackground,
    needsActivateOnFGSwitch, backgroundAndForeground, dontGetFrontClicks,
    ignoreChildDiedEvents, is32BitCompatible, notHighLevelEventAware,
    onlyLocalHLEvents, notStationeryAware, dontUseTextEditServices,
    reserved, reserved, reserved,
    384 * 1024, /* preferred */
    256 * 1024  /* minimum */
};

/* The signature (owner) resource. */
data 'LFtt' (0, "Owner resource") { $"09" $"54656C6574656B7374" };
