#!/usr/bin/env python3
"""Generates src/font.s: the glyphs Teletekst draws, as Super Hi-Res masks.

The characters come from Daniel Hepper's font8x8 (public domain, the IBM VGA
font): font8x8_basic.h for ASCII and font8x8_ext_latin.h for U+00A0-U+00FF.
The server sends Mac Roman, so codes 80-FF are mapped through Unicode; the
few Mac Roman characters without a Latin-1 glyph are blank.

Each glyph is 8 lines of 4 bytes, one nibble per pixel (left pixel in the
high nibble): F where the pixel is ink, 0 where it is paper. The program
colours a line with  paper EOR ((ink EOR paper) AND mask).

Glyphs 0-255 are the characters; 256-319 are the Teletekst block-graphics
patterns 0-63 (bit 0 top left, 1 top right, 2 middle left ... 5 bottom
right), in thirds of 3, 3 and 2 lines.

    python3 tools/mkfont.py > src/font.s
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def load(name):
    text = open(os.path.join(HERE, name)).read()
    return [[int(b, 16) for b in re.findall(r"0x([0-9A-Fa-f]{2})", row)]
            for row in re.findall(r"\{([^{}]*)\}", text.split("= {", 1)[1])]


basic = load("font8x8_basic.h")      # U+0000-U+007F
latin = load("font8x8_ext_latin.h")  # U+00A0-U+00FF
assert len(basic) == 128 and len(latin) == 96


def glyph(code):
    """8 rows of 8 pixels, bit 0 leftmost (font8x8's order)."""
    if 0x20 <= code < 0x7F:
        return basic[code]
    if code >= 0x80:
        u = ord(bytes([code]).decode("mac_roman"))
        if 0xA0 <= u <= 0xFF:
            return latin[u - 0xA0]
    return [0] * 8


def mosaic(p):
    thirds = [0, 0, 0, 1, 1, 1, 2, 2]
    rows = []
    for line in range(8):
        t = thirds[line]
        left, right = p >> (2 * t) & 1, p >> (2 * t + 1) & 1
        rows.append((0x0F if left else 0) | (0xF0 if right else 0))
    return rows


def masks(rows):
    out = []
    for r in rows:
        for x in range(0, 8, 2):
            out.append((0xF0 if r >> x & 1 else 0) | (0x0F if r >> (x + 1) & 1 else 0))
    return out


print("* Generated by tools/mkfont.py from font8x8 (public domain). Do not edit.")
print("* 320 glyphs of 8 lines x 4 bytes: characters 0-255, then mosaics 0-63.")
print("glyphs")
for code in range(256):
    print(" hex " + "".join("%02X" % b for b in masks(glyph(code))) + " ; %02X" % code)
for p in range(64):
    print(" hex " + "".join("%02X" % b for b in masks(mosaic(p))) + " ; mosaic %d" % p)
