#!/usr/bin/env python3
"""Generates src/iotta_logo.h: the iotta logo as a 1-bit QuickDraw bitmap.

The logo (tools/iotta-logo.png, green on transparent) is cropped, scaled to
HEIGHT pixels and thresholded on its alpha channel; ink is black. Needs
Pillow.

    python3 tools/mklogo.py > src/iotta_logo.h
"""
import os

from PIL import Image

HEIGHT = 24
THRESHOLD = 80  # alpha 0-255: at least this much is ink

here = os.path.dirname(os.path.abspath(__file__))
alpha = Image.open(os.path.join(here, "iotta-logo.png")).convert("RGBA").split()[3]
alpha = alpha.crop(alpha.getbbox())
width = round(alpha.size[0] * HEIGHT / alpha.size[1])
alpha = alpha.resize((width, HEIGHT), Image.LANCZOS)
row_bytes = (width + 15) // 16 * 2

print("/* Generated by tools/mklogo.py from tools/iotta-logo.png. Do not edit. */")
print("#define LOGO_W %d" % width)
print("#define LOGO_H %d" % HEIGHT)
print("#define LOGO_ROWBYTES %d" % row_bytes)
print("static const unsigned char logo_bits[LOGO_H * LOGO_ROWBYTES] = {")
for y in range(HEIGHT):
    row = bytearray(row_bytes)
    for x in range(width):
        if alpha.getpixel((x, y)) >= THRESHOLD:
            row[x >> 3] |= 0x80 >> (x & 7)
    print("    " + ", ".join("0x%02X" % b for b in row) + ",")
print("};")
